BEGIN;

DROP TABLE IF EXISTS egress_log;
DROP TABLE IF EXISTS secret_ref;
DROP TABLE IF EXISTS github_app_install;
DROP TABLE IF EXISTS run_event;
DROP TABLE IF EXISTS run;
DROP TYPE  IF EXISTS run_status;
DROP TABLE IF EXISTS lease;
DROP TABLE IF EXISTS claimable_work;
DROP TABLE IF EXISTS runner;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS app_user;
DROP TYPE  IF EXISTS user_role;
DROP TABLE IF EXISTS tenant;

COMMIT;
